### ISSUE TITLE
Make http_simple work

### ISSUE THREAD

**Issue by piscisaureus** [tjanczuk/httpsys#18]
I tried it (node 0.8.8 x64), but it didn't work.

Steps to reproduce:
- modify `benchmark/http_simple.js` to use `httpsys`
- hammer `http://localhost:8000/bytes/100` with some benchmarking tool (I used `ab`)
- profit! 

```
pid 5664
Listening at http://127.0.0.1:8000/
create storedBytes[n]

events.js:66
        throw arguments[1]; // Unhandled 'error' event
                       ^
Error: Error sending response data. System error 0.
    at HttpServer.Server._notify_error_and_dispose (D:\node4\benchmark\node_modules\httpsys\lib\httpsys.js:473:42)
    at HttpServer.Server._on_error_writing (D:\node4\benchmark\node_modules\httpsys\lib\httpsys.js:512:10)
    at HttpServer.Server._dispatch (D:\node4\benchmark\node_modules\httpsys\lib\httpsys.js:417:46)
    at httpsys.httpsys_init.callback (D:\node4\benchmark\node_modules\httpsys\lib\httpsys.js:81:27)
    at ServerResponse._initiate_send_next (D:\node4\benchmark\node_modules\httpsys\lib\httpsys.js:331:53)
    at ServerRequest._on_end_request (D:\node4\benchmark\node_modules\httpsys\lib\httpsys.js:135:30)
    at HttpServer.Server._on_end_request (D:\node4\benchmark\node_modules\httpsys\lib\httpsys.js:487:24)
    at HttpServer.Server._dispatch (D:\node4\benchmark\node_modules\httpsys\lib\httpsys.js:417:46)
    at httpsys.httpsys_init.callback (D:\node4\benchmark\node_modules\httpsys\lib\httpsys.js:81:27)
```

**Comment by tjanczuk** [comment]
At the moment httpsys works only with node x86. I will leave this bug open to enable x64 support.

**Comment by ghost** [comment]
Who's using x86 today for server application development ? Windows Server is 64 bits only since 2008 R2.

Could x64 be the priority, and x86 provided for legacy purposes only ?

**Comment by tjanczuk** [comment]
Httpsys currently supports both x86 and x64 node.js versions. This bug remains open to ensure the sample works correctly.
