### ISSUE TITLE
Socket._getHeader error

### ISSUE THREAD

**Issue by rodrigopolo** [tjanczuk/httpsys#33]
I installed the module:

```
npm install httpsys
```

Inserted at the first line of the app.js the following code:

``` javascript
require('httpsys').slipstream();
```

When running the app and refreshing on the browser I got the following error:

```
C:\node\apps\tests\node_modules\mongoose\lib\utils.js:419
        throw err;
              ^
Error: Response headers cannot be accessed after they have been sent to the client.
    at Socket._getHeader (C:\node\apps\tests\node_modules\httpsys\lib\Socket.js:286:15)
    at ServerResponse.getHeader (C:\node\apps\tests\node_modules\httpsys\lib\ServerResponse.js:42:25)
    at exports.token.sock (C:\node\apps\tests\node_modules\express\node_modules\connect\lib\middleware\logger.js:229:26)
    at ServerResponse.res.end (C:\node\apps\tests\node_modules\express\node_modules\connect\lib\middleware\logger.js:149:20)
    at Promise.<anonymous> (C:\node\apps\tests\node_modules\express\node_modules\connect\lib\middleware\session.js:285:13)
    at Promise.<anonymous> (C:\node\apps\tests\node_modules\mongoose\node_modules\mpromise\lib\promise.js:162:8)
    at Promise.EventEmitter.emit (events.js:95:17)
    at Promise.emit (C:\node\apps\tests\node_modules\mongoose\node_modules\mpromise\lib\promise.js:79:38)
    at Promise.fulfill (C:\node\apps\tests\node_modules\mongoose\node_modules\mpromise\lib\promise.js:92:20)
    at C:\node\apps\tests\node_modules\mongoose\lib\query.js:1823:13
```

I commented the line 419 on ...\node_modules\mongoose\lib\utils.js just to see what happened:

```
Assertion failed: !(handle->flags & UV_HANDLE_CLOSED), file src\win\async.c, line 34
```

I'm using Node v0.10.15 x64 on Windows 8 x64 v 6.3.9431 with the following modules

``` javascript
"dependencies": {
  "passport-twitter": "0.1.5",
  "mongoose": "~3.6.17",
  "express": "~3.3.5",
  "express-sessions": "~1.0.5",
  "passport": "~0.1.17",
  "passport-remember-me": "0.0.1",
  "ejs": "~0.8.4",
  "utils": "~0.1.4",
  "twit": "~1.1.9",
  "connect": "~2.8.5",
  "socket.io": "~0.9.16",
  "ejs-locals": "~1.0.2"
}
```

So I guess the _"there are no changes required in the code of your application"_ isn't true...

What could be the cause of the error?

**Comment by tjanczuk** [comment]
Thank you for the report. I expect there will be more such compatibility issues that need fixing.

**Comment by rodrigopolo** [comment]
I actually still have this issue.
